----------------------------------------------------------------------------
-- tb_svd_array.vhd
--
-- Functional + numerical testbench for the one-sided Jacobi SVD core.
--
-- Loads an 8x8 Q1.16 input from svd_input.mem, streams it through the
-- AXI4-Stream wrapper, drains the final rotated A matrix, computes
-- the L2 norm of each column, sorts the norms descending, and
-- compares against svd_sigma.mem with a loose tolerance.
--
-- The .mem files are regenerated by tools/svd_golden_ref.py and
-- verified against NumPy by tools/verify_golden.py.
--
-- Tolerance: |err| < 2^-10 relative (~1e-3), chosen loosely for the
-- Q1.16 CORDIC + fixed-sweep schedule.
--
-- Status: UNTESTED. Compile with VHDL-2008 (uses std.textio).
----------------------------------------------------------------------------

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use ieee.math_real.all;
library std;
use std.textio.all;

library work;
use work.svd_pkg.all;

entity tb_svd_array is
end entity;

architecture rtl of tb_svd_array is
  constant ROWS_C     : integer := 8;
  constant COLS_C     : integer := 8;
  constant CLK_PERIOD : time    := 10 ns;

  signal aclk    : std_logic := '0';
  signal aresetn : std_logic := '0';

  signal s_axis_tdata  : std_logic_vector(DATA_WIDTH-1 downto 0) := (others => '0');
  signal s_axis_tvalid : std_logic := '0';
  signal s_axis_tlast  : std_logic := '0';
  signal s_axis_tready : std_logic;

  signal m_axis_tdata  : std_logic_vector(DATA_WIDTH-1 downto 0);
  signal m_axis_tvalid : std_logic;
  signal m_axis_tlast  : std_logic;
  signal m_axis_tready : std_logic := '1';

  signal stim_done    : boolean := false;
  signal recv_done    : boolean := false;
  signal check_done   : boolean := false;
  signal check_pass   : boolean := false;
  signal timeout_fire : boolean := false;

  -- Storage for the drained matrix (row-major Q1.16 integers)
  type   int_arr_t is array (natural range <>) of integer;
  signal drained    : int_arr_t(0 to ROWS_C*COLS_C-1) := (others => 0);
  signal recv_cnt   : integer                         := 0;

  impure function read_mem_file (fname : string; n : integer) return int_arr_t is
    file     f    : text open read_mode is fname;
    variable l    : line;
    variable v    : integer;
    variable out_arr : int_arr_t(0 to n-1);
  begin
    for i in 0 to n-1 loop
      readline(f, l);
      read(l, v);
      out_arr(i) := v;
    end loop;
    return out_arr;
  end function;

  function abs_int (x : integer) return integer is
  begin
    if x < 0 then
      return -x;
    end if;
    return x;
  end function;

  function fix_sqrt (x : real) return real is
  begin
    if x < 0.0 then
      return 0.0;
    end if;
    return sqrt(x);
  end function;
begin
  ------------------------------------------------------------------
  -- DUT
  ------------------------------------------------------------------
  uut : entity work.svd_array_top
    generic map (ROWS => ROWS_C, COLS => COLS_C, DATA_W => DATA_WIDTH)
    port map (
      aclk          => aclk,
      aresetn       => aresetn,
      s_axis_tdata  => s_axis_tdata,
      s_axis_tvalid => s_axis_tvalid,
      s_axis_tlast  => s_axis_tlast,
      s_axis_tready => s_axis_tready,
      m_axis_tdata  => m_axis_tdata,
      m_axis_tvalid => m_axis_tvalid,
      m_axis_tlast  => m_axis_tlast,
      m_axis_tready => m_axis_tready
    );

  ------------------------------------------------------------------
  -- 100 MHz clock
  ------------------------------------------------------------------
  clk_gen : process
  begin
    while not (check_done or timeout_fire) loop
      aclk <= '0';
      wait for CLK_PERIOD/2;
      aclk <= '1';
      wait for CLK_PERIOD/2;
    end loop;
    wait;
  end process;

  ------------------------------------------------------------------
  -- Stimulus: load svd_input.mem, stream, then idle
  ------------------------------------------------------------------
  stim : process
    variable inp : int_arr_t(0 to ROWS_C*COLS_C-1);
  begin
    inp := read_mem_file("svd_input.mem", ROWS_C*COLS_C);

    aresetn <= '0';
    wait for 5 * CLK_PERIOD;
    aresetn <= '1';
    wait for 2 * CLK_PERIOD;

    for i in 0 to ROWS_C*COLS_C-1 loop
      s_axis_tdata  <= std_logic_vector(to_signed(inp(i), DATA_WIDTH));
      s_axis_tvalid <= '1';
      if i = ROWS_C*COLS_C-1 then
        s_axis_tlast <= '1';
      else
        s_axis_tlast <= '0';
      end if;
      wait until rising_edge(aclk) and s_axis_tready = '1';
    end loop;

    s_axis_tvalid <= '0';
    s_axis_tlast  <= '0';
    stim_done <= true;
    wait;
  end process;

  ------------------------------------------------------------------
  -- Receive the drained matrix into `drained`.
  ------------------------------------------------------------------
  recv : process (aclk)
  begin
    if rising_edge(aclk) then
      if m_axis_tvalid = '1' and m_axis_tready = '1' then
        if recv_cnt < ROWS_C*COLS_C then
          drained(recv_cnt) <= to_integer(signed(m_axis_tdata));
          recv_cnt <= recv_cnt + 1;
        end if;
        if m_axis_tlast = '1' then
          recv_done <= true;
        end if;
      end if;
    end if;
  end process;

  ------------------------------------------------------------------
  -- Check: compute column norms, sort desc, compare to svd_sigma.mem
  ------------------------------------------------------------------
  check : process
    constant SCALE   : real := real(2**16);
    variable sigma_q : int_arr_t(0 to COLS_C-1);
    variable norms   : real_vector(0 to COLS_C-1);
    variable norms_q : int_arr_t(0 to COLS_C-1);
    variable acc     : real;
    variable v_real  : real;
    variable tmp     : real;
    variable tmp_q   : integer;
    variable passed  : boolean := true;
    variable tol_q   : integer;
    variable diff_q  : integer;
    variable l       : line;
  begin
    -- Wait for drain to finish, then give one extra cycle for the last word.
    wait until recv_done;
    wait for 2 * CLK_PERIOD;

    sigma_q := read_mem_file("svd_sigma.mem", COLS_C);

    -- Column norms over the drained matrix.
    for j in 0 to COLS_C-1 loop
      acc := 0.0;
      for i in 0 to ROWS_C-1 loop
        v_real := real(drained(i*COLS_C + j)) / SCALE;
        acc    := acc + v_real * v_real;
      end loop;
      norms(j) := fix_sqrt(acc);
    end loop;

    -- Sort norms descending (bubble, 8 elements).
    for pass_i in 0 to COLS_C-2 loop
      for j in 0 to COLS_C-2-pass_i loop
        if norms(j) < norms(j+1) then
          tmp         := norms(j);
          norms(j)    := norms(j+1);
          norms(j+1)  := tmp;
        end if;
      end loop;
    end loop;

    -- Quantize sorted norms back to Q1.16 for comparison.
    for i in 0 to COLS_C-1 loop
      norms_q(i) := integer(round(norms(i) * SCALE));
    end loop;

    -- Tolerance: 2^-10 relative to top singular value; floor to a few ULPs.
    tol_q := sigma_q(0) / 1024;
    if tol_q < 64 then
      tol_q := 64;
    end if;

    report "---- SVD numerical check ----" severity note;
    for i in 0 to COLS_C-1 loop
      diff_q := abs_int(norms_q(i) - sigma_q(i));
      write(l, string'("sigma["));
      write(l, i);
      write(l, string'("]: expected="));
      write(l, sigma_q(i));
      write(l, string'("  got="));
      write(l, norms_q(i));
      write(l, string'("  diff="));
      write(l, diff_q);
      if diff_q > tol_q then
        write(l, string'("  FAIL (tol="));
        write(l, tol_q);
        write(l, string'(")"));
        passed := false;
      else
        write(l, string'("  ok"));
      end if;
      writeline(output, l);
    end loop;

    if passed then
      report "SVD CHECK: PASS (all 8 singular values within tol)" severity note;
      check_pass <= true;
    else
      report "SVD CHECK: FAIL" severity failure;
    end if;

    check_done <= true;
    wait;
  end process;

  ------------------------------------------------------------------
  -- Safety timeout
  ------------------------------------------------------------------
  timeout : process
  begin
    wait for 200 us;
    if not check_done then
      report "TB: timeout before check completed" severity failure;
      timeout_fire <= true;
    end if;
    wait;
  end process;
end architecture rtl;
