----------------------------------------------------------------------------
-- svd_jacobi_blv.vhd
--
-- BLV-ordered one-sided Jacobi SVD orchestrator, parameterised on N.
--
-- PAIR_UNITS = COLS/2 instances of svd_pair_pipeline run in lockstep.
-- A tiny schedule mux routes column pairs from svd_blv_schedule_pkg
-- (auto-generated by tools/gen_blv_schedule_pkg.py) into each
-- pipeline. Pairs are disjoint within a step, so N/2 pipelines
-- read/write distinct columns of the shared register-file matrix A
-- without conflict.
--
-- Supported COLS values: 4, 8, 16 (whatever the schedule pkg provides).
----------------------------------------------------------------------------

library IEEE;
use IEEE.STD_LOGIC_1164.all;
use IEEE.NUMERIC_STD.all;
use work.svd_pkg.all;
use work.svd_blv_schedule_pkg.all;

entity svd_jacobi_blv is
  generic (
    DATA_W : integer := DATA_WIDTH;
    ROWS   : integer := 4;
    COLS   : integer := 4;
    SWEEPS : integer := 4
  );
  port (
    clk        : in  std_logic;
    rst_n      : in  std_logic;

    din_valid  : in  std_logic;
    din        : in  data_t;

    start      : in  std_logic;
    done       : out std_logic;

    dout_ready : in  std_logic;
    dout       : out data_t;
    dout_valid : out std_logic;
    dout_last  : out std_logic
  );
end entity svd_jacobi_blv;

architecture rtl of svd_jacobi_blv is
  constant PAIR_UNITS : integer := COLS / 2;
  constant STEPS      : integer := COLS - 1;

  type   mat_t is array (0 to ROWS-1, 0 to COLS-1) of data_t;
  signal A : mat_t;

  -- Schedule lookup. We expose helper functions that pick the right
  -- generated constant based on COLS; this keeps the architecture body
  -- generic without needing VHDL-2008 config-time generics support.
  function sched_p (step : integer; unit : integer) return integer is
  begin
    case COLS is
      when 4  => return SCHEDULE_P_N4(step)(unit);
      when 8  => return SCHEDULE_P_N8(step)(unit);
      when 16 => return SCHEDULE_P_N16(step)(unit);
      when others =>
        report "svd_jacobi_blv: unsupported COLS value "
               & integer'image(COLS) severity failure;
        return 0;
    end case;
  end function;

  function sched_q (step : integer; unit : integer) return integer is
  begin
    case COLS is
      when 4  => return SCHEDULE_Q_N4(step)(unit);
      when 8  => return SCHEDULE_Q_N8(step)(unit);
      when 16 => return SCHEDULE_Q_N16(step)(unit);
      when others =>
        report "svd_jacobi_blv: unsupported COLS value "
               & integer'image(COLS) severity failure;
        return 0;
    end case;
  end function;

  type ctrl_state_t is (
    LOAD_WAIT, STEP_START, STEP_RUN, STEP_WAIT,
    DRAIN_START, DRAIN
  );
  signal state : ctrl_state_t;

  signal load_cnt      : integer range 0 to ROWS*COLS;
  signal start_pending : std_logic;
  signal step_idx      : integer range 0 to STEPS;
  signal sweep_cnt     : integer range 0 to SWEEPS;
  signal drain_cnt     : integer range 0 to ROWS*COLS;

  -- Per-pipeline signals.
  type   sl_arr_t  is array (0 to PAIR_UNITS-1) of std_logic;
  type   data_arr_t is array (0 to PAIR_UNITS-1) of data_t;
  type   idx_arr_t  is array (0 to PAIR_UNITS-1) of integer range 0 to ROWS;

  signal pu_start      : sl_arr_t   := (others => '0');
  signal pu_in_a_p     : data_arr_t;
  signal pu_in_a_q     : data_arr_t;
  signal pu_req_phase  : sl_arr_t;
  signal pu_req_rowidx : idx_arr_t;
  signal pu_req_valid  : sl_arr_t;
  signal pu_out_p      : data_arr_t;
  signal pu_out_q      : data_arr_t;
  signal pu_out_rowidx : idx_arr_t;
  signal pu_out_valid  : sl_arr_t;
  signal pu_skip       : sl_arr_t;
  signal pu_done       : sl_arr_t;

  signal step_done_mask : std_logic_vector(PAIR_UNITS-1 downto 0);
begin
  ------------------------------------------------------------------------
  -- Instantiate PAIR_UNITS parallel svd_pair_pipeline units.
  ------------------------------------------------------------------------
  gen_pu : for k in 0 to PAIR_UNITS-1 generate
    u_pu : entity work.svd_pair_pipeline
      generic map (DATA_W => DATA_W, ROWS => ROWS)
      port map (
        clk         => clk,
        rst_n       => rst_n,
        start       => pu_start(k),
        in_a_p      => pu_in_a_p(k),
        in_a_q      => pu_in_a_q(k),
        req_phase   => pu_req_phase(k),
        req_row_idx => pu_req_rowidx(k),
        req_valid   => pu_req_valid(k),
        out_new_p   => pu_out_p(k),
        out_new_q   => pu_out_q(k),
        out_row_idx => pu_out_rowidx(k),
        out_valid   => pu_out_valid(k),
        skip        => pu_skip(k),
        done        => pu_done(k)
      );
  end generate;

  ------------------------------------------------------------------------
  -- Combinational row data to each pipeline from the schedule + A.
  ------------------------------------------------------------------------
  gen_route : for k in 0 to PAIR_UNITS-1 generate
    process (A, pu_req_valid, pu_req_rowidx, step_idx)
      variable p : integer range 0 to COLS-1;
      variable q : integer range 0 to COLS-1;
      variable r : integer range 0 to ROWS;
    begin
      p := sched_p(step_idx, k);
      q := sched_q(step_idx, k);
      r := pu_req_rowidx(k);
      if pu_req_valid(k) = '1' and r < ROWS then
        pu_in_a_p(k) <= A(r, p);
        pu_in_a_q(k) <= A(r, q);
      else
        pu_in_a_p(k) <= (others => '0');
        pu_in_a_q(k) <= (others => '0');
      end if;
    end process;
  end generate;

  ------------------------------------------------------------------------
  -- Main FSM
  ------------------------------------------------------------------------
  process (clk)
    variable all_done : boolean;
  begin
    if rising_edge(clk) then
      if rst_n = '0' then
        state          <= LOAD_WAIT;
        load_cnt       <= 0;
        start_pending  <= '0';
        step_idx       <= 0;
        sweep_cnt      <= 0;
        drain_cnt      <= 0;
        step_done_mask <= (others => '0');
        done           <= '0';
        dout           <= (others => '0');
        dout_valid     <= '0';
        dout_last      <= '0';
        for k in 0 to PAIR_UNITS-1 loop
          pu_start(k) <= '0';
        end loop;
      else
        for k in 0 to PAIR_UNITS-1 loop
          pu_start(k) <= '0';
        end loop;
        dout_valid <= '0';
        dout_last  <= '0';

        case state is
          when LOAD_WAIT =>
            if din_valid = '1' and load_cnt < ROWS*COLS then
              A(load_cnt / COLS, load_cnt mod COLS) <= din;
              load_cnt <= load_cnt + 1;
            end if;
            if start = '1' then
              start_pending <= '1';
            end if;
            if (start = '1' or start_pending = '1') and load_cnt >= ROWS*COLS then
              sweep_cnt      <= 0;
              step_idx       <= 0;
              start_pending  <= '0';
              step_done_mask <= (others => '0');
              state          <= STEP_START;
              report "svd_jacobi_blv: start accepted, load_cnt="
                     & integer'image(load_cnt) severity note;
            end if;

          when STEP_START =>
            for k in 0 to PAIR_UNITS-1 loop
              pu_start(k) <= '1';
            end loop;
            step_done_mask <= (others => '0');
            state <= STEP_RUN;

          when STEP_RUN =>
            for k in 0 to PAIR_UNITS-1 loop
              if pu_out_valid(k) = '1' then
                A(pu_out_rowidx(k), sched_p(step_idx, k)) <= pu_out_p(k);
                A(pu_out_rowidx(k), sched_q(step_idx, k)) <= pu_out_q(k);
              end if;
              if pu_done(k) = '1' then
                step_done_mask(k) <= '1';
              end if;
            end loop;

            all_done := true;
            for k in 0 to PAIR_UNITS-1 loop
              if step_done_mask(k) = '0' and pu_done(k) = '0' then
                all_done := false;
              end if;
            end loop;
            if all_done then
              state <= STEP_WAIT;
            end if;

          when STEP_WAIT =>
            if step_idx = STEPS - 1 then
              step_idx <= 0;
              if sweep_cnt = SWEEPS - 1 then
                state <= DRAIN_START;
              else
                sweep_cnt <= sweep_cnt + 1;
                report "svd_jacobi_blv: completed sweep "
                       & integer'image(sweep_cnt + 1)
                       severity note;
                state <= STEP_START;
              end if;
            else
              step_idx <= step_idx + 1;
              state    <= STEP_START;
            end if;

          when DRAIN_START =>
            drain_cnt <= 0;
            done      <= '1';
            state     <= DRAIN;

          when DRAIN =>
            if dout_ready = '1' then
              dout_valid <= '1';
              dout       <= A(drain_cnt / COLS, drain_cnt mod COLS);
              if drain_cnt = ROWS*COLS - 1 then
                dout_last <= '1';
              end if;
              if drain_cnt < ROWS*COLS - 1 then
                drain_cnt <= drain_cnt + 1;
              end if;
            end if;
        end case;
      end if;
    end if;
  end process;
end architecture rtl;
