----------------------------------------------------------------------------
-- svd_blv_schedule_pkg.vhd
--
-- AUTO-GENERATED by tools/gen_blv_schedule_pkg.py. Do not edit by hand.
-- Rerun whenever SUPPORTED_NS in the generator changes.
--
-- Each N supplies two flat tables SCHEDULE_P_N<n> and SCHEDULE_Q_N<n>,
-- each a (N-1) x (N/2) array of column indices. svd_jacobi_blv's
-- schedule mux reads these at (step, unit).
----------------------------------------------------------------------------

library IEEE;
use IEEE.STD_LOGIC_1164.all;

package svd_blv_schedule_pkg is
  -- N = 4: 3 steps x 2 pairs/step
  type step_n4_t is array (0 to 1) of integer range 0 to 3;
  type sched_n4_t is array (0 to 2) of step_n4_t;
  constant SCHEDULE_P_N4 : sched_n4_t := (
    0 => (0, 2),
    1 => (0, 1),
    2 => (0, 1)
  );
  constant SCHEDULE_Q_N4 : sched_n4_t := (
    0 => (1, 3),
    1 => (3, 2),
    2 => (2, 3)
  );

  -- N = 8: 7 steps x 4 pairs/step
  type step_n8_t is array (0 to 3) of integer range 0 to 7;
  type sched_n8_t is array (0 to 6) of step_n8_t;
  constant SCHEDULE_P_N8 : sched_n8_t := (
    0 => (0, 2, 3, 4),
    1 => (0, 1, 2, 3),
    2 => (0, 5, 1, 2),
    3 => (0, 4, 3, 1),
    4 => (0, 3, 2, 1),
    5 => (0, 2, 1, 6),
    6 => (0, 1, 4, 5)
  );
  constant SCHEDULE_Q_N8 : sched_n8_t := (
    0 => (1, 7, 6, 5),
    1 => (7, 6, 5, 4),
    2 => (6, 7, 4, 3),
    3 => (5, 6, 7, 2),
    4 => (4, 5, 6, 7),
    5 => (3, 4, 5, 7),
    6 => (2, 3, 7, 6)
  );

  -- N = 16: 15 steps x 8 pairs/step
  type step_n16_t is array (0 to 7) of integer range 0 to 15;
  type sched_n16_t is array (0 to 14) of step_n16_t;
  constant SCHEDULE_P_N16 : sched_n16_t := (
    0 => (0, 2, 3, 4, 5, 6, 7, 8),
    1 => (0, 1, 2, 3, 4, 5, 6, 7),
    2 => (0, 13, 1, 2, 3, 4, 5, 6),
    3 => (0, 12, 11, 1, 2, 3, 4, 5),
    4 => (0, 11, 10, 9, 1, 2, 3, 4),
    5 => (0, 10, 9, 8, 7, 1, 2, 3),
    6 => (0, 9, 8, 7, 6, 5, 1, 2),
    7 => (0, 8, 7, 6, 5, 4, 3, 1),
    8 => (0, 7, 6, 5, 4, 3, 2, 1),
    9 => (0, 6, 5, 4, 3, 2, 1, 14),
    10 => (0, 5, 4, 3, 2, 1, 12, 13),
    11 => (0, 4, 3, 2, 1, 10, 11, 12),
    12 => (0, 3, 2, 1, 8, 9, 10, 11),
    13 => (0, 2, 1, 6, 7, 8, 9, 10),
    14 => (0, 1, 4, 5, 6, 7, 8, 9)
  );
  constant SCHEDULE_Q_N16 : sched_n16_t := (
    0 => (1, 15, 14, 13, 12, 11, 10, 9),
    1 => (15, 14, 13, 12, 11, 10, 9, 8),
    2 => (14, 15, 12, 11, 10, 9, 8, 7),
    3 => (13, 14, 15, 10, 9, 8, 7, 6),
    4 => (12, 13, 14, 15, 8, 7, 6, 5),
    5 => (11, 12, 13, 14, 15, 6, 5, 4),
    6 => (10, 11, 12, 13, 14, 15, 4, 3),
    7 => (9, 10, 11, 12, 13, 14, 15, 2),
    8 => (8, 9, 10, 11, 12, 13, 14, 15),
    9 => (7, 8, 9, 10, 11, 12, 13, 15),
    10 => (6, 7, 8, 9, 10, 11, 15, 14),
    11 => (5, 6, 7, 8, 9, 15, 14, 13),
    12 => (4, 5, 6, 7, 15, 14, 13, 12),
    13 => (3, 4, 5, 15, 14, 13, 12, 11),
    14 => (2, 3, 15, 14, 13, 12, 11, 10)
  );

end package svd_blv_schedule_pkg;
