#!/usr/bin/env python3
"""Emit svd_blv_schedule_pkg.vhd — round-robin schedule as a VHDL constant.

Writes one `constant SCHEDULE_N{n} : sched_n{n}_t := (...)` per supported
N, plus `constant SCHEDULE_P/_Q` arrays for the orchestrator to index
with (step, unit).

The output is a VHDL-2008 package consumed by svd_jacobi_blv.vhd when
built with generic N in {4, 8, 16}.
"""

from __future__ import annotations

from pathlib import Path

from round_robin_schedule import round_robin, verify_schedule


SUPPORTED_NS = (4, 8, 16)
OUT_PATH = (Path(__file__).resolve().parent.parent
            / "kung_svd" / "kung_svd.srcs" / "sources_1" / "new"
            / "svd_blv_schedule_pkg.vhd")


def emit_schedule_body(n: int) -> list[str]:
    """Flat tables SCHEDULE_P_N<n>(step)(unit), SCHEDULE_Q_N<n>(step)(unit)."""
    steps = round_robin(n)
    verify_schedule(steps, n)
    units = n // 2
    nsteps = n - 1

    lines = []
    lines.append(f"  -- N = {n}: {nsteps} steps x {units} pairs/step")
    lines.append(f"  type step_n{n}_t is array (0 to {units - 1}) "
                 f"of integer range 0 to {n - 1};")
    lines.append(f"  type sched_n{n}_t is array (0 to {nsteps - 1}) "
                 f"of step_n{n}_t;")
    for which, idx in (("P", 0), ("Q", 1)):
        rows = []
        for s in range(nsteps):
            vals = ", ".join(str(steps[s][u][idx]) for u in range(units))
            rows.append(f"    {s} => ({vals})")
        lines.append(f"  constant SCHEDULE_{which}_N{n} : sched_n{n}_t := (")
        lines.append(",\n".join(rows))
        lines.append("  );")
    return lines


def main() -> None:
    header = [
        "----------------------------------------------------------------------------",
        "-- svd_blv_schedule_pkg.vhd",
        "--",
        "-- AUTO-GENERATED by tools/gen_blv_schedule_pkg.py. Do not edit by hand.",
        "-- Rerun whenever SUPPORTED_NS in the generator changes.",
        "--",
        "-- Each N supplies two flat tables SCHEDULE_P_N<n> and SCHEDULE_Q_N<n>,",
        "-- each a (N-1) x (N/2) array of column indices. svd_jacobi_blv's",
        "-- schedule mux reads these at (step, unit).",
        "----------------------------------------------------------------------------",
        "",
        "library IEEE;",
        "use IEEE.STD_LOGIC_1164.all;",
        "",
        "package svd_blv_schedule_pkg is",
    ]
    footer = [
        "end package svd_blv_schedule_pkg;",
        "",
    ]
    body: list[str] = []
    for n in SUPPORTED_NS:
        body.extend(emit_schedule_body(n))
        body.append("")

    out = "\n".join(header + body + footer)
    OUT_PATH.write_text(out)
    print(f"wrote {OUT_PATH}")
    for n in SUPPORTED_NS:
        print(f"  N={n}: {n - 1} steps x {n // 2} pairs")


if __name__ == "__main__":
    main()
